---
- hosts: '{{ tgt_host }}'
  vars:
    filebeat_config_output_redis: 'internal-aaaaamazonaws.com:6379'
    filebeat_config_paths:
      - /var/log/nginx/*.log
      - /var/log/httpd/*_log
  roles:
    - filebeat
---
- hosts: '{{ tgt_host }}'
  vars:
    dnsmasq_listenaddress: "127.0.0.1"
    dnsmasq_externaldns: "192.168.0.2"
  roles:
    - dnsmasq
