##### By ansible
###
# Module: system
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-module-system.html

- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  cpu.metrics: ["normalized_percentages"]
  enabled: true

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 5m
  metricsets:
    - uptime
