plugin: aws_ec2
cache_timeout: 60
regions:
  - sa-east-1
aws_profile: 'myprofile'
hostnames:
  - instance-id
  - tag:Name
  - private_ip_address
  - public_ip_address
  - public_dns_name
keyed_groups:
  - key: placement.region
  - key: key_name
  - key: tags.Name
compose:
  # set the ansible_host variable to connect with the private IP address without changing the hostname
  ansible_host: private_ip_address
